/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wmouMaCO9ek
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Dispatch, SetStateAction, useContext, useState } from "react";
import { NFTContract } from "@/types/nft";
import { fetchNftContract } from "@/toolkit/graphql";
import { Progress } from "../ChallengeCreator";
import { NetworkContext } from "@/toolkit/blockchain";

export default function RewardNFTForm({
  rewardNft,
  setRewardNft,
  rewardTitle,
  setRewardTitle,
  rewardDescription,
  setRewardDescription,
  rewardMediaLink,
  setRewardMediaLink,
  setProgress,
}: {
  rewardNft: NFTContract | undefined;
  setRewardNft: Dispatch<SetStateAction<NFTContract | undefined>>;
  rewardTitle: string | undefined;
  setRewardTitle: Dispatch<SetStateAction<string | undefined>>;
  rewardDescription: string | undefined;
  setRewardDescription: Dispatch<SetStateAction<string | undefined>>;
  rewardMediaLink: string | undefined;
  setRewardMediaLink: Dispatch<SetStateAction<string | undefined>>;
  setProgress: Dispatch<SetStateAction<Progress>>;
}) {
  const [rewardNftId, setRewardNftId] = useState(rewardNft?.id || "");
  const { network } = useContext(NetworkContext)!;

  const onSubmit = async () => {
    const nft = await fetchNftContract(rewardNftId, network);
    if (nft == null) {
      alert("NFT not found");
      return;
    }

    setRewardNft(nft);
  };

  return (
    <div className="mx-auto max-w-md space-y-6">
      <div className="space-y-2 text-left">
        <h2 className="text-xl font-semibold">Reward NFT Details</h2>
        <p className="text-gray-500 dark:text-gray-400">
          Enter some details about your reward NFT below. These fields are all only necessary if you plan on minting the
          reward NFT through the challenge contract.
        </p>
      </div>
      <div className="space-y-6">
        <div>
          <label htmlFor="nft-id">Reward NFT Contract ID</label>
          <div className="grid gap-4">
            <div className="space-y-2">
              <Input
                value={rewardNftId}
                onChange={(e) => setRewardNftId(e.target.value)}
                id="nft-id"
                placeholder="Enter the NFT ID"
              />
            </div>
          </div>
        </div>
        <div>
          <label htmlFor="nft-id">Title</label>
          <div className="grid gap-4">
            <div className="space-y-2">
              <Input
                value={rewardTitle}
                onChange={(e) => setRewardTitle(e.target.value)}
                id="rewardTitle"
                placeholder="Enter a title for the reward nfts"
              />
            </div>
          </div>
        </div>
        <div>
          <label htmlFor="nft-id">Description</label>
          <div className="grid gap-4">
            <div className="space-y-2">
              <Input
                value={rewardDescription}
                onChange={(e) => setRewardDescription(e.target.value)}
                id="rewardDescription"
                placeholder="Enter a description for the challenge"
              />
            </div>
          </div>
        </div>
        <div>
          <label htmlFor="nft-id">Media Link</label>
          <div className="grid gap-4">
            <div className="space-y-2">
              <Input
                value={rewardMediaLink}
                onChange={(e) => setRewardMediaLink(e.target.value)}
                id="mediaLink"
                placeholder="Enter a description for the challenge"
              />
            </div>
          </div>
        </div>
        <div className="flex justify-between">
          <Button onClick={() => setProgress(Progress.ChallengeDetails)} variant="outline">
            Previous
          </Button>
          <Button onClick={onSubmit}>Next</Button>
        </div>
      </div>
    </div>
  );
}
