/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rwTSgVn5ARK
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { useEffect, useState } from "react";
import { Wallet, useMbWallet } from "@mintbase-js/react";
import { Button } from "./ui/button";

export function Web3Toggle() {
  const { isConnected, selector, activeAccountId, disconnect } = useMbWallet();

  const [wallet, setWallet] = useState<Wallet | null>(null);
  useEffect(() => {
    (async () => {
      if (isConnected) {
        setWallet(await selector.wallet());
      } else {
        setWallet(null);
      }
    })();
  }, [isConnected]);

  return (
    <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6 absolute right-0 top-10">
      <div className="ml-auto flex flex-row items-center gap-4">
        {wallet != null && (
          <div className="mr-4 flex flex-col items-center">
            <p>You are connected as {activeAccountId}</p>
            <Button
              onClick={() => {
                wallet.signOut();
                disconnect();
              }}
            >
              Disconnect
            </Button>
          </div>
        )}
      </div>
    </header>
  );
}
